# Generated by Django 4.2.11 on 2024-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('sub', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
